### ISSUE TITLE
is use of fakedate really necessary?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-prod_util#53]
Seemingly one of the tests requires fakedate be installed on ubuntu. But somehow not Intel - I don't understand that.

If we are going to require fakedate we need to check for it in the Cmake build, not just fail the test if fakedate is not present.

But do we really need to introduce this dependency? I don't see at fist glance where it is being used...

@AlexanderRichert-NOAA any comments?

**Comment by AlexanderRichert-NOAA** [comment]
I put it in for testing the nhour utility, because it can either use a specified date _or_ get the current datetime from the system. Using faketime in the CI testing (see the scripts in tests/) lets us test the latter scenario but without having to do our own calculation of the result based on the current time.

**Comment by AlexanderRichert-NOAA** [comment]
BTW it is there in the Intel workflow, but for some reason I put the install command at the bottom right before the ctest run...

**Comment by edwardhartnett** [comment]
OK, I will fix the cmake...
