### ISSUE TITLE
spack package is called prod-util, not prod_util - can we change it?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-prod_util#66]
When this package was put into spack, long long ago, it was done so as prod-util, not prod_util.

Should we care? Changing would be a big problem. Do we just live with this?

@AlexanderRichert-NOAA what do you think?

**Comment by AlexanderRichert-NOAA** [comment]
Short answer, we live with it but change the module name to 'prod_util'.

We ran into this recently (https://github.com/JCSDA/spack-stack/issues/780). Basically, spack doesn't allow packages with underscores in the names. So in spack-stack, the env module configuration renames the module to 'prod_util' so that we can keep using `module load prod_util` (we've added this as of spack-stack-1.5.0; I think a user of 1.4.1 would have to use the hyphenated name in their module load). There shouldn't be any further impact from the name discrepancy.
